set -g mode-keys vi
set -g default-terminal "${TERM}"
set -gs terminal-overrides ",*:RGB"
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g prefix '`'
bind -g '`' send-prefix
bind -g r source ~/.config/tmux/tmux.conf

set-hook -g after-new-session 'run ~/.config/tmux/themes/selector.sh'
