#!/usr/bin/env bash

_script_path="$(dirname ${BASH_SOURCE[0]})"
source "$_script_path/../selector.sh"
mode=$(detect_terminal_bg)

# Ubuntu brand palette
UBUNTU_ORANGE="#E95420"
UBUNTU_ORANGE_LIGHT="#F4AA61"
UBUNTU_AUBERGINE_DARK="#300A24"
UBUNTU_AUBERGINE_MID="#77216F"
UBUNTU_AUBERGINE_DEEP="#2C001E"
UBUNTU_WARM_GREY="#AEA79F"
UBUNTU_COOL_GREY="#333333"
UBUNTU_WHITE="#FFFFFF"
UBUNTU_LIGHT_GREY="#F2F2F2"

# Rounded powerline separators (Nerd Fonts E0B4 / E0B6)
RIGHT_ICON=""
LEFT_ICON=""

# Nerd Font icons
UBUNTU_LOGO="󰕈"  # nf-md-ubuntu
ICON_FOLDER="󰉋"  # nf-md-folder
ICON_BRANCH=""  # nf-dev-git_branch
ICON_CLOCK="󰥔"

# Git status indicator colors
BLUE="#88B4E7"
GREEN="#8AE234"
RED="#EF2929"
YELLOW="#F4AA61"

if [[ $mode == "dark" ]]; then
    SOURCE="$UBUNTU_ORANGE"
    PRIMARY="$UBUNTU_ORANGE_LIGHT"
    SECONDARY="$UBUNTU_WARM_GREY"
    TERCIARY="$UBUNTU_AUBERGINE_MID"

    FG="$UBUNTU_WHITE"
    TAGBG="$UBUNTU_AUBERGINE_MID"
    TAGFG="$UBUNTU_WHITE"
    TAGFGDIM="$UBUNTU_WARM_GREY"

    ACTIVE_TAB_FG="$UBUNTU_WHITE"
    ACTIVE_TAB_BG="$UBUNTU_ORANGE"
    TAB_BG="$UBUNTU_AUBERGINE_DEEP"
else
    SOURCE="$UBUNTU_ORANGE"
    PRIMARY="$UBUNTU_AUBERGINE_MID"
    SECONDARY="$UBUNTU_COOL_GREY"
    TERCIARY="$UBUNTU_ORANGE_LIGHT"

    FG="$UBUNTU_COOL_GREY"
    TAGBG="$UBUNTU_ORANGE"
    TAGFG="$UBUNTU_WHITE"
    TAGFGDIM="$UBUNTU_COOL_GREY"

    ACTIVE_TAB_FG="$UBUNTU_WHITE"
    ACTIVE_TAB_BG="$UBUNTU_ORANGE"
    TAB_BG="$UBUNTU_LIGHT_GREY"
fi
