#!/usr/bin/env bash

_script_path="$(dirname ${BASH_SOURCE[0]})"
source "$_script_path/../selector.sh"
mode=$(detect_terminal_bg)

BLUE=#3487ed
RED=#DB0000
WHITE=#ffffff

LEFT_ICON=""
RIGHT_ICON=""

BLACK="#1d1d1f"
WHITE="#FFFFFF"

ILUMINATED_NAVY="#4F505C"
BRILLIANT_YELLOW="#FFD497"
GLOWING_CORAL="#EDA09C"
LUMINOUS_ORCHID="#D1B6CB"
CYAN="#99b8e5"

ACCENT="$GLOWING_CORAL"
PRIMARY=$LUMINOUS_ORCHID
if [[ $mode == dark ]]; then
	PRIMARY=$LUMINOUS_ORCHID
	TAGBG="$BRILLIANT_YELLOW"
    TAGFG="$ILUMINATED_NAVY"
else
	PRIMARY=$GLOWING_CORAL
    TAGBG=$LUMINOUS_ORCHID
    TAGFG="$ILUMINATED_NAVY"
fi
