#!/usr/bin/env bash

_script_path="$(dirname ${BASH_SOURCE[0]})"
source "$_script_path/../selector.sh"
mode=$(detect_terminal_bg)

# Kanagawa palette (rebelot/kanagawa.nvim)
# Wave = dark variant, Lotus = light variant
SUMI_INK="#16161D"
FUJI_WHITE="#DCD7BA"
OLD_WHITE="#C8C093"
SPRING_GREEN="#98BB6C"
AUTUMN_GREEN="#76946A"
SAMURAI_RED="#E82424"
SURIMI_ORANGE="#FFA066"
CARP_YELLOW="#E6C384"
SAKURA_PINK="#D27E99"
SPRING_BLUE="#7FB4CA"

LOTUS_INK="#545464"
LOTUS_WHITE="#F2ECBC"
LOTUS_GREEN="#6F894E"
LOTUS_RED="#C84053"
LOTUS_ORANGE="#CC6D00"
LOTUS_YELLOW="#DE9800"
LOTUS_PINK="#B35B79"
LOTUS_TEAL="#6693BF"

# icons
# ''
# ''
# ''
# ''
LEFT_ICON=""
RIGHT_ICON=""

if [[ $mode == "dark" ]]; then
	SOURCE="$SURIMI_ORANGE"
	PRIMARY="$SPRING_GREEN"
	SECONDARY="$AUTUMN_GREEN"
	TERCIARY="$SAKURA_PINK"

	BLUE=$SPRING_BLUE
	GREEN=$AUTUMN_GREEN
	RED=$SAMURAI_RED
	YELLOW=$CARP_YELLOW
	WHITE=$FUJI_WHITE

	FG="$FUJI_WHITE"
    TAGBG="$SPRING_GREEN"
    TAGFGDIM="$SUMI_INK"
    TAGFG="$SUMI_INK"

	ACTIVE_TAB_FG="$SUMI_INK"
	ACTIVE_TAB_BG="$SURIMI_ORANGE"
	TAB_BG="$OLD_WHITE"
else
	SOURCE="$LOTUS_RED"
	PRIMARY="$LOTUS_GREEN"
	SECONDARY="$LOTUS_TEAL"
	TERCIARY="$LOTUS_PINK"

	BLUE=$LOTUS_TEAL
	GREEN=$LOTUS_GREEN
	RED=$LOTUS_RED
	YELLOW=$LOTUS_YELLOW
	WHITE=$LOTUS_WHITE

	FG="$LOTUS_INK"
    TAGFG="$LOTUS_WHITE"
    TAGFGDIM="$LOTUS_INK"
    TAGBG="$LOTUS_GREEN"

	ACTIVE_TAB_FG="$LOTUS_WHITE"
	ACTIVE_TAB_BG="$LOTUS_ORANGE"
	TAB_BG="$LOTUS_WHITE"
fi
