#!/usr/bin/env bash

mode=$(defaults read -g AppleInterfaceStyle 2>/dev/null || echo Light)

#
#
#3396D3
#FFF0CE
#EBCB90
#EEEEEE
COZY_WHITE="#FBF9F8"
SESAME_BLACK="#151515"
PEACHY_CLAY="#e5bda1"
WARM_TERRA="#c88566"
IVORY_SAND="#f0e9d3"
MINT_JADE="#cfddbb"
DUSKY_PINE="#747564"

# icons
# ''
# ''
# ''
# ''
LEFT_ICON=""
RIGHT_ICON=""
SOURCE="#fdca6a"
PRIMARY="#9fff19"
SECONDARY="#3454BD"

if [[ $mode == "Dark" ]]; then
	TERCIARY="$WARM_TERRA"

	BLUE=#3487ed
	GREEN=#00802f
	RED=#DB0000
	WHITE=#ffffff

    TAG_FG="$SESAME_BLACK"
    TAG_FGDIM="$SESAME_BLACK"
    TAG_BG="$SECONDARY"

	ACTIVE_TAB_FG="$SESAME_BLACK"
	ACTIVE_TAB_BG="$SOURCE"
	TAB_BG="$COZY_WHITE"
else

	BLUE=#3487ed
	GREEN=#00802f
	RED=#DB0000
	WHITE=#ffffff

    TAG_BG="$SECONDARY"
    TAG_FGDIM="$COZY_WHITE"
    TAG_FG="$COZY_WHITE"

	ACTIVE_TAB_FG="$SESAME_BLACK"
	ACTIVE_TAB_BG="$SOURCE"
	TAB_BG="$SESAME_BLACK"
fi
